# Generated by Django 4.2.7 on 2023-12-03 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0002_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user_control.setor'),
        ),
    ]
