# Generated by Django 4.2.7 on 2023-12-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0003_customuser_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='sector',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
