# Generated by Django 4.2.7 on 2023-11-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0002_remove_descricao_relatorio_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='created_by',
        ),
    ]
