# Generated by Django 4.2.7 on 2023-11-29 16:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0004_remove_rotina_situacao_rotina_prazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotina',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('REALIZADO_PRAZO', 'Realizado no Prazo'), ('PREVISAO_EXECUCAO', 'Previsão de Execução'), ('REALIZADO_FORA_PRAZO', 'Realizado Fora do Prazo'), ('INVENTARIO_GERAL', 'Inventário Geral'), ('JUSTIFICADO', 'Justificado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='prazo',
            field=models.CharField(choices=[('Diário', 'Diário'), ('Segunda-Feira', 'Segunda-Feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-Feira', 'Quarta-Feira'), ('Quinta-Feira', 'Quinta-Feira'), ('Sexta-Feira', 'Sexta-Feira'), ('5° Dia Util', '5° Dia Util')], default='Diário', max_length=15),
        ),
        migrations.CreateModel(
            name='StatusDiarioRotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('REALIZADO_PRAZO', 'Realizado no Prazo'), ('PREVISAO_EXECUCAO', 'Previsão de Execução'), ('REALIZADO_FORA_PRAZO', 'Realizado Fora do Prazo'), ('INVENTARIO_GERAL', 'Inventário Geral'), ('JUSTIFICADO', 'Justificado')], default='PENDENTE', max_length=20)),
                ('rotina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_diarios', to='app_control.rotina')),
            ],
            options={
                'unique_together': {('rotina', 'data')},
            },
        ),
    ]
