# Generated by Django 4.2.7 on 2023-12-03 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0007_statusdiariorotina_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Responsavel',
        ),
    ]
