# Generated by Django 4.2.7 on 2023-12-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0009_alter_rotina_setor_delete_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotina',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('REALIZADO PRAZO', 'Realizado no Prazo'), ('PREVISAO EXECUCAO', 'Previsão de Execução'), ('REALIZADO FORA_PRAZO', 'Realizado Fora do Prazo'), ('INVENTARIO GERAL', 'Inventário Geral'), ('JUSTIFICADO', 'Justificado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='statusdiariorotina',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('REALIZADO PRAZO', 'Realizado no Prazo'), ('PREVISAO EXECUCAO', 'Previsão de Execução'), ('REALIZADO FORA_PRAZO', 'Realizado Fora do Prazo'), ('INVENTARIO GERAL', 'Inventário Geral'), ('JUSTIFICADO', 'Justificado')], default='PENDENTE', max_length=20),
        ),
    ]
