# Generated by Django 4.2.7 on 2023-12-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0010_alter_rotina_status_alter_statusdiariorotina_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotina',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('REALIZADO_PRAZO', 'Realizado no Prazo'), ('PREVISAO_EXECUCAO', 'Previsão de Execução'), ('REALIZADO_FORA_PRAZO', 'Realizado Fora do Prazo'), ('INVENTARIO_GERAL', 'Inventário Geral'), ('JUSTIFICADO', 'Justificado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='statusdiariorotina',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('REALIZADO_PRAZO', 'Realizado no Prazo'), ('PREVISAO_EXECUCAO', 'Previsão de Execução'), ('REALIZADO_FORA_PRAZO', 'Realizado Fora do Prazo'), ('INVENTARIO_GERAL', 'Inventário Geral'), ('JUSTIFICADO', 'Justificado')], default='PENDENTE', max_length=20),
        ),
    ]
