# Generated by Django 4.2.7 on 2023-12-06 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_control', '0011_alter_rotina_status_alter_statusdiariorotina_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricao_relatorio',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='description', to=settings.AUTH_USER_MODEL),
        ),
    ]
